# Generated by Django 2.2.6 on 2019-11-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwallet',
            name='parentEmail',
            field=models.EmailField(default='abc@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='studentwallet',
            name='studentEmail',
            field=models.EmailField(default='abc@gmail.com', max_length=50),
        ),
    ]
